### ISSUE TITLE
这个你还继续写嘛

### ISSUE THREAD

**Issue by roy2651** [JoeyCurry/react-native-agora-videochat#4]
兄弟，你这个还继续写嘛？
我看了你的截图已经完成了很多？
我想知道的是呼入这种你是怎么写的，如果app在后台也能弹窗到接听，挂断的的页面嘛
不知道我表达的你明白了

**Comment by JoeyCurry** [comment]
已经没写了，换公司了
如果app在后台 就同学消息通知把app切换到前台来 然后展示页面

**Comment by roy2651** [comment]
好的，谢谢
